extends:
  - airbnb
  - prettier
  - prettier/react
plugins:
  - prettier
parser: babel-eslint
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true
env:
  es6: true
  node: true
  browser: true
rules:
  prettier/prettier: error
  # No proptypes for now
  react/prop-types: warn
  # Console is allowed for now
  no-console: off
  # Required for mongodb, should be disabled in the places used though
  no-underscore-dangle: warn
  # We probabily dont have problems with this, with the newest node version
  no-restricted-syntax: warn

