language: node_js
node_js: node

notifications:
  email: false

before_install: yarn global add greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update

script:
  - yarn lint

after_script: greenkeeper-lockfile-upload
